---
- name: Install PostgreSQL
  hosts: all
  become: true

  vars:
    postgres_user: dbadmin
    postgres_password: SecureP@ss1
    postgres_db: demo_db

  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create DB user
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        state: present

    - name: Create database
      become_user: postgres
      postgresql_db:
        name: "{{ postgres_db }}"
        owner: "{{ postgres_user }}"
