---
- name: Install MongoDB and create user/database
  hosts: all
  become: true

  vars:
    mongodb_repo_key: https://pgp.mongodb.com/server-6.0.asc
    mongodb_repo: 'deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/6.0 multiverse'
    mongodb_user: myappuser
    mongodb_password: StrongPass123!
    mongodb_database: myappdb
    mongodb_role: readWrite

  tasks:
    - name: Install dependencies
      apt:
        name:
          - gnupg
          - curl
        state: present
        update_cache: true

    - name: Create keyring directory if it doesn't exist
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Add MongoDB GPG key
      get_url:
        url: "{{ mongodb_repo_key }}"
        dest: /usr/share/keyrings/mongodb-server-6.0.gpg
        mode: '0644'

    - name: Add MongoDB repository
      copy:
        dest: /etc/apt/sources.list.d/mongodb-org-6.0.list
        content: |
          {{ mongodb_repo }}
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Ensure MongoDB is started and enabled
      service:
        name: mongod
        state: started
        enabled: true

    - name: Wait for MongoDB to become available
      wait_for:
        host: 127.0.0.1
        port: 27017
        delay: 5
        timeout: 30

    - name: Create MongoDB user with database
      community.mongodb.mongodb_user:
        login_host: localhost
        login_port: 27017
        database: "{{ mongodb_database }}"
        name: "{{ mongodb_user }}"
        password: "{{ mongodb_password }}"
        roles: ["{{ mongodb_role }}"]
        state: present
