---
- name: Install MongoDB 7.0 and create user/database on Ubuntu 22.04
  hosts: all
  become: true

  vars:
    mongodb_version: "7.0"
    mongodb_gpg_key_url: https://pgp.mongodb.com/server-7.0.gpg
    mongodb_gpg_key_path: /usr/share/keyrings/mongodb-server-7.0.gpg
    mongodb_repo_file: /etc/apt/sources.list.d/mongodb-org-7.0.list
    mongodb_repo_entry: >
      deb [arch=amd64,signed-by={{ mongodb_gpg_key_path }}]
      https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse
    mongodb_user: myappuser
    mongodb_password: StrongPass123!
    mongodb_database: myappdb
    mongodb_role: readWrite

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Download and install MongoDB 7 GPG key (binary format)
      get_url:
        url: "{{ mongodb_gpg_key_url }}"
        dest: "{{ mongodb_gpg_key_path }}"
        mode: '0644'
        force: yes

    - name: Add MongoDB 7.0 APT repository securely with signed-by
      copy:
        dest: "{{ mongodb_repo_file }}"
        content: "{{ mongodb_repo_entry }}"
        mode: '0644'

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install MongoDB 7.0 packages
      apt:
        name: mongodb-org
        state: present

    - name: Ensure MongoDB is running and enabled
      service:
        name: mongod
        state: started
        enabled: true

    - name: Wait for MongoDB to become available
      wait_for:
        host: 127.0.0.1
        port: 27017
        delay: 5
        timeout: 30

    - name: Create MongoDB user
      community.mongodb.mongodb_user:
        login_host: localhost
        login_port: 27017
        database: "{{ mongodb_database }}"
        name: "{{ mongodb_user }}"
        password: "{{ mongodb_password }}"
        roles: ["{{ mongodb_role }}"]
        state: present
