- hosts: all
  become: true
  tasks:

    - name: Install required packages
      apt:
        name:
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Download and move MongoDB GPG key to trusted.gpg.d
      shell: |
        curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
        gpg --dearmor -o /etc/apt/trusted.gpg.d/mongodb-server-7.0.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/mongodb-server-7.0.gpg

    - name: Add MongoDB repository
      copy:
        content: >
          deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse
        dest: /etc/apt/sources.list.d/mongodb-org-7.0.list
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB
      service:
        name: mongod
        state: started
        enabled: yes
