- name: Install PostgreSQL (latest from PGDG) and create 'managedb' on Ubuntu 22.04
  hosts: all
  become: true

  tasks:
    - name: Temporarily set full permissions on Ansible remote tmp dir
      file:
        path: /tmp/.ansible_remote_tmp
        state: directory
        mode: '0777'

    - name: Install required packages
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Create keyring directory for PGDG if not present
      file:
        path: /usr/share/postgresql-common/pgdg
        state: directory
        mode: '0755'

    - name: Download PostgreSQL APT repo key
      get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
        mode: '0644'

    - name: Add PostgreSQL APT repository with signed-by
      copy:
        dest: /etc/apt/sources.list.d/pgdg.list
        content: |
          deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
        mode: '0644'

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install latest PostgreSQL from PGDG (currently PostgreSQL 16)
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL is started and enabled
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Create database 'managedb'
      become_user: postgres
      postgresql_db:
        name: managedb

    - name: Restore secure permissions to Ansible remote tmp dir
      file:
        path: /tmp/.ansible_remote_tmp
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0700'
